/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    orders: Order;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('el' | 'en') | ('el' | 'en')[];
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    availability: Availability;
    'site-settings': SiteSetting;
    labels: Label;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
  };
  locale: 'el' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  category: 'queen-bees' | 'queen-cells' | 'bee-nucs';
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Price in euros
   */
  price?: number | null;
  /**
   * Show “price on request” instead of the price
   */
  priceHidden?: boolean | null;
  /**
   * Inactive products are hidden from the shop
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  product: number | Product;
  quantity: number;
  name: string;
  email: string;
  phone: string;
  notes?: string | null;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  /**
   * Language the customer ordered in
   */
  locale: 'el' | 'en';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  image?: T;
  price?: T;
  priceHidden?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  product?: T;
  quantity?: T;
  name?: T;
  email?: T;
  phone?: T;
  notes?: T;
  status?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
    scrollLabel?: string | null;
    /**
     * MP4 or WebM, muted and looping. Keep it short and light (under ~10 MB).
     */
    video?: (number | null) | Media;
  };
  offer?: {
    title?: string | null;
    cardCta?: string | null;
    queenBees?: {
      title?: string | null;
      eyebrow?: string | null;
      description?: string | null;
      image?: (number | null) | Media;
    };
    queenCells?: {
      title?: string | null;
      eyebrow?: string | null;
      description?: string | null;
      image?: (number | null) | Media;
    };
    beeNucs?: {
      title?: string | null;
      eyebrow?: string | null;
      description?: string | null;
      image?: (number | null) | Media;
    };
  };
  why?: {
    title?: string | null;
    heritage?: {
      title?: string | null;
      description?: string | null;
      /**
       * Shown inside a hexagon — set the focal point on the photo to keep the subject in view.
       */
      image?: (number | null) | Media;
    };
    healthy?: {
      title?: string | null;
      description?: string | null;
      /**
       * Shown inside a hexagon — set the focal point on the photo to keep the subject in view.
       */
      image?: (number | null) | Media;
    };
    service?: {
      title?: string | null;
      description?: string | null;
      /**
       * Shown inside a hexagon — set the focal point on the photo to keep the subject in view.
       */
      image?: (number | null) | Media;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  story?: {
    title?: string | null;
    /**
     * Leave a blank line between paragraphs.
     */
    description?: string | null;
    /**
     * Leave empty to show the placeholder photo.
     */
    image?: (number | null) | Media;
  };
  beekeeping?: {
    title?: string | null;
    /**
     * Leave a blank line between paragraphs.
     */
    description?: string | null;
    /**
     * Leave empty to show the placeholder photo.
     */
    image?: (number | null) | Media;
  };
  queenRearing?: {
    title?: string | null;
    /**
     * Leave a blank line between paragraphs.
     */
    description?: string | null;
    /**
     * Leave empty to show the placeholder photo.
     */
    image?: (number | null) | Media;
  };
  nucs?: {
    title?: string | null;
    /**
     * Leave a blank line between paragraphs.
     */
    description?: string | null;
    /**
     * Leave empty to show the placeholder photo.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  /**
   * Shown as a badge on the home page card. Leave empty to hide the badge.
   */
  queenBees?: {
    from?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
    to?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  };
  /**
   * Shown as a badge on the home page card. Leave empty to hide the badge.
   */
  queenCells?: {
    from?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
    to?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  };
  /**
   * Shown as a badge on the home page card. Leave empty to hide the badge.
   */
  beeNucs?: {
    from?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
    to?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in the copyright line and as the logo's text fallback.
   */
  siteName?: string | null;
  /**
   * Shown in the navbar and the footer.
   */
  logo?: (number | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  footer?: {
    tagline?: string | null;
    address?: string | null;
    email?: string | null;
    phone?: string | null;
    /**
     * Shown in the bottom bar, e.g. melissokomiakritis.gr
     */
    domain?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: number;
  nav?: {
    home?: string | null;
    about?: string | null;
    queens?: string | null;
    cells?: string | null;
    nucs?: string | null;
    faqs?: string | null;
    gallery?: string | null;
    contact?: string | null;
  };
  footer?: {
    quick_links?: string | null;
    contact_heading?: string | null;
    rights?: string | null;
  };
  shop?: {
    title?: string | null;
    shipping_notice?: string | null;
    price_hidden?: string | null;
    order_button?: string | null;
  };
  order_form?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    quantity?: string | null;
    notes?: string | null;
    submit?: string | null;
    success?: string | null;
    error?: string | null;
  };
  home?: {
    available?: string | null;
  };
  about?: {
    discover?: string | null;
  };
  gallery?: {
    title?: string | null;
  };
  faqs?: {
    title?: string | null;
  };
  contact?: {
    title?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        scrollLabel?: T;
        video?: T;
      };
  offer?:
    | T
    | {
        title?: T;
        cardCta?: T;
        queenBees?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              description?: T;
              image?: T;
            };
        queenCells?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              description?: T;
              image?: T;
            };
        beeNucs?:
          | T
          | {
              title?: T;
              eyebrow?: T;
              description?: T;
              image?: T;
            };
      };
  why?:
    | T
    | {
        title?: T;
        heritage?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
        healthy?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
        service?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  story?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  beekeeping?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  queenRearing?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  nucs?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  queenBees?:
    | T
    | {
        from?: T;
        to?: T;
      };
  queenCells?:
    | T
    | {
        from?: T;
        to?: T;
      };
  beeNucs?:
    | T
    | {
        from?: T;
        to?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        address?: T;
        email?: T;
        phone?: T;
        domain?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        home?: T;
        about?: T;
        queens?: T;
        cells?: T;
        nucs?: T;
        faqs?: T;
        gallery?: T;
        contact?: T;
      };
  footer?:
    | T
    | {
        quick_links?: T;
        contact_heading?: T;
        rights?: T;
      };
  shop?:
    | T
    | {
        title?: T;
        shipping_notice?: T;
        price_hidden?: T;
        order_button?: T;
      };
  order_form?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        quantity?: T;
        notes?: T;
        submit?: T;
        success?: T;
        error?: T;
      };
  home?:
    | T
    | {
        available?: T;
      };
  about?:
    | T
    | {
        discover?: T;
      };
  gallery?:
    | T
    | {
        title?: T;
      };
  faqs?:
    | T
    | {
        title?: T;
      };
  contact?:
    | T
    | {
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}